import Mathlib.Data.Finset.Card
import Mathlib.Data.Fintype.Perm
import Mathlib.Data.Fintype.Pi
import Mathlib.Data.Fintype.Powerset
import Mathlib.Data.Fintype.Prod

/-!
# The first missing cotransverse map occurs in dimension four

Lean 4.33.1 / mathlib v4.33.1 formalization of
`cotransverse_maps_dimension_four.tex`.

Vertices of `[n]` are represented by finite subsets of `Fin n`. Thus
`DirectedEdge A B` means that `B` is obtained from `A` by inserting one
coordinate. The level part of the category generated by symmetries and
cotransverse degeneracies is represented by words in coordinate permutations
and two-coordinate comparators.

The source-at-most-three corollary in the paper invokes an external unique
coface-factorization theorem. Rather than introduce an axiom for that cited
result, the final implication is formalized below with the factorization and
the cotransversality of cofaces as explicit hypotheses.
-/

namespace CotransverseDimensionFour

open Function

abbrev Cube (n : Nat) := Finset (Fin n)

abbrev RankVertex (n k : Nat) := {A : Cube n // A.card = k}

/-- A directed edge (cover relation) in the Boolean cube. -/
def DirectedEdge {n : Nat} (A B : Cube n) : Prop :=
  ∃ i, i ∉ A ∧ B = insert i A

instance instDecidableDirectedEdge {n : Nat} (A B : Cube n) :
    Decidable (DirectedEdge A B) := by
  unfold DirectedEdge
  infer_instance

/-- A map of cubes is cotransverse when it preserves directed edges. -/
def Cotransverse {m n : Nat} (f : Cube m → Cube n) : Prop :=
  ∀ ⦃A B⦄, DirectedEdge A B → DirectedEdge (f A) (f B)

instance instDecidableCotransverse {m n : Nat} (f : Cube m → Cube n) :
    Decidable (Cotransverse f) := by
  unfold Cotransverse
  infer_instance

lemma DirectedEdge.card_eq {n : Nat} {A B : Cube n}
    (h : DirectedEdge A B) : B.card = A.card + 1 := by
  rcases h with ⟨i, hi, rfl⟩
  simp [hi]

/-- Along every vertex, a cotransverse endomorphism shifts rank by the
rank of the image of the empty vertex. -/
lemma rank_eq_rank_empty_add {n : Nat} (f : Cube n → Cube n)
    (hf : Cotransverse f) (A : Cube n) :
    (f A).card = (f ∅).card + A.card := by
  classical
  induction A using Finset.induction_on with
  | empty => simp
  | @insert i A hi ih =>
      have hedge : DirectedEdge A (insert i A) := ⟨i, hi, rfl⟩
      have himage := DirectedEdge.card_eq (hf hedge)
      rw [himage, ih]
      simp [hi, Nat.add_assoc]

/-- Rank preservation (Lemma 1.1 of the manuscript). -/
theorem rank_preservation {n : Nat} (f : Cube n → Cube n)
    (hf : Cotransverse f) (A : Cube n) :
    (f A).card = A.card := by
  have htop := rank_eq_rank_empty_add f hf (Finset.univ : Cube n)
  have hle : (f (Finset.univ : Cube n)).card ≤ n := by
    simpa using Finset.card_le_univ (f (Finset.univ : Cube n))
  have hempty : (f ∅).card = 0 := by
    simp only [Finset.card_univ, Fintype.card_fin] at htop
    omega
  simpa [hempty] using rank_eq_rank_empty_add f hf A

theorem fixes_bottom {n : Nat} (f : Cube n → Cube n)
    (hf : Cotransverse f) : f ∅ = ∅ := by
  apply Finset.card_eq_zero.mp
  simpa using rank_preservation f hf (∅ : Cube n)

theorem fixes_top {n : Nat} (f : Cube n → Cube n)
    (hf : Cotransverse f) : f Finset.univ = Finset.univ := by
  apply (Finset.card_eq_iff_eq_univ (f Finset.univ)).mp
  simpa using rank_preservation f hf (Finset.univ : Cube n)

/-! ## The generated level monoid and the first-fold obstruction -/

/-- Relabel the coordinates of a cube by a permutation. -/
def permMap {n : Nat} (σ : Equiv.Perm (Fin n)) : Cube n → Cube n :=
  fun A => A.map σ.toEmbedding

/-- The comparator which replaces the two bits at `p,q` by their maximum
and minimum (the maximum being placed at `p`). -/
def comparator {n : Nat} (p q : Fin n) : Cube n → Cube n :=
  fun A => if q ∈ A ∧ p ∉ A then insert p (A.erase q) else A

/-- `f` globally folds the pair `p,q`. -/
def GloballyFolds {n : Nat} (f : Cube n → Cube n) (p q : Fin n) : Prop :=
  ∀ A, p ∉ A → q ∉ A → f (insert p A) = f (insert q A)

instance instDecidableGloballyFolds {n : Nat} (f : Cube n → Cube n)
    (p q : Fin n) : Decidable (GloballyFolds f p q) := by
  unfold GloballyFolds
  exact @Fintype.decidableForallFintype _ _
    (fun A => inferInstance) inferInstance

lemma comparator_globallyFolds {n : Nat} {p q : Fin n} (hpq : p ≠ q) :
    GloballyFolds (comparator p q) p q := by
  intro A hp hq
  simp [comparator, hp, hq, hpq, hpq.symm]

lemma permMap_injective {n : Nat} (σ : Equiv.Perm (Fin n)) :
    Injective (permMap σ) := by
  exact Finset.map_injective σ.toEmbedding

/-- A level generator: a coordinate permutation or a comparator.  Allowing
all coordinate permutations and all pairs gives the same level monoid as the
adjacent symmetries and adjacent cotransverse degeneracies in the manuscript,
because every pair is conjugate to an adjacent pair. -/
inductive Step (n : Nat) where
  | perm (σ : Equiv.Perm (Fin n))
  | fold (p q : Fin n) (hpq : p ≠ q)
  deriving DecidableEq

def Step.eval {n : Nat} : Step n → Cube n → Cube n
  | .perm σ => permMap σ
  | .fold p q _ => comparator p q

/-- The head of the list is applied first, in ordinary functional order. -/
def evalWord {n : Nat} : List (Step n) → Cube n → Cube n
  | [], A => A
  | s :: w, A => evalWord w (s.eval A)

def Generated {n : Nat} (f : Cube n → Cube n) : Prop :=
  ∃ w : List (Step n), evalWord w = f

lemma evalWord_append {n : Nat} (u v : List (Step n)) :
    evalWord (u ++ v) = evalWord v ∘ evalWord u := by
  funext A
  induction u generalizing A with
  | nil => rfl
  | cons s u ih =>
      simp only [List.cons_append, evalWord, Function.comp_apply]
      exact ih (s.eval A)

lemma generated_id {n : Nat} : Generated (id : Cube n → Cube n) :=
  ⟨[], rfl⟩

lemma generated_perm {n : Nat} (σ : Equiv.Perm (Fin n)) :
    Generated (permMap σ) :=
  ⟨[.perm σ], rfl⟩

lemma generated_comparator {n : Nat} (p q : Fin n) (hpq : p ≠ q) :
    Generated (comparator p q) :=
  ⟨[.fold p q hpq], rfl⟩

lemma Generated.comp {n : Nat} {f g : Cube n → Cube n}
    (hg : Generated g) (hf : Generated f) : Generated (g ∘ f) := by
  rcases hf with ⟨u, rfl⟩
  rcases hg with ⟨v, rfl⟩
  exact ⟨u ++ v, evalWord_append u v⟩

lemma evalWord_noninjective_globallyFolds {n : Nat} (w : List (Step n))
    (hni : ¬Injective (evalWord w)) :
    ∃ p q, p ≠ q ∧ GloballyFolds (evalWord w) p q := by
  induction w with
  | nil =>
      exact False.elim (hni fun _ _ h => h)
  | cons s w ih =>
      cases s with
      | fold p q hpq =>
          refine ⟨p, q, hpq, ?_⟩
          intro A hp hq
          exact congrArg (evalWord w) (comparator_globallyFolds hpq A hp hq)
      | perm σ =>
          have htail : ¬Injective (evalWord w) := by
            intro h
            apply hni
            exact h.comp (permMap_injective σ)
          rcases ih htail with ⟨p, q, hpq, hfold⟩
          have hpq' : σ.symm p ≠ σ.symm q := by
            intro h
            apply hpq
            simpa using congrArg σ h
          refine ⟨σ.symm p, σ.symm q, hpq', ?_⟩
          intro A hp hq
          have hp' : p ∉ permMap σ A := by
            simpa [permMap] using hp
          have hq' : q ∉ permMap σ A := by
            simpa [permMap] using hq
          have h := hfold (permMap σ A) hp' hq'
          simpa [evalWord, Step.eval, permMap] using h

/-- First-fold obstruction (Lemma 5.2 of the manuscript, in its equivalent
non-injective form for a finite endomorphism). -/
theorem first_fold_obstruction {n : Nat} {f : Cube n → Cube n}
    (hgen : Generated f) (hni : ¬Injective f) :
    ∃ p q, p ≠ q ∧ GloballyFolds f p q := by
  rcases hgen with ⟨w, rfl⟩
  exact evalWord_noninjective_globallyFolds w hni

lemma Cotransverse.comp {l m n : Nat} {f : Cube l → Cube m}
    {g : Cube m → Cube n} (hg : Cotransverse g) (hf : Cotransverse f) :
    Cotransverse (g ∘ f) := by
  intro A B hAB
  exact hg (hf hAB)

lemma permMap_cotransverse {n : Nat} (σ : Equiv.Perm (Fin n)) :
    Cotransverse (permMap σ) := by
  intro A B hAB
  rcases hAB with ⟨i, hi, rfl⟩
  refine ⟨σ i, ?_, ?_⟩
  · simpa [permMap] using hi
  · simp [permMap]

lemma comparator_cotransverse_three :
    ∀ p q : Fin 3, p ≠ q → Cotransverse (comparator p q) := by
  decide

lemma comparator_cotransverse_two :
    ∀ p q : Fin 2, p ≠ q → Cotransverse (comparator p q) := by
  decide

lemma comparator_cotransverse_four :
    ∀ p q : Fin 4, p ≠ q → Cotransverse (comparator p q) := by
  decide

/-- In the dimensions used below, the finite check that every level generator
preserves covers. This is the direct Boolean-lattice verification of the
formulas for `σᵢ` and `γᵢ`. -/
lemma step_cotransverse_three : ∀ s : Step 3, Cotransverse s.eval := by
  intro s
  cases s with
  | perm σ => exact permMap_cotransverse σ
  | fold p q hpq => exact comparator_cotransverse_three p q hpq

lemma step_cotransverse_two : ∀ s : Step 2, Cotransverse s.eval := by
  intro s
  cases s with
  | perm σ => exact permMap_cotransverse σ
  | fold p q hpq => exact comparator_cotransverse_two p q hpq

lemma step_cotransverse_four : ∀ s : Step 4, Cotransverse s.eval := by
  intro s
  cases s with
  | perm σ => exact permMap_cotransverse σ
  | fold p q hpq => exact comparator_cotransverse_four p q hpq

lemma evalWord_cotransverse_three (w : List (Step 3)) :
    Cotransverse (evalWord w) := by
  induction w with
  | nil =>
      intro A B hAB
      exact hAB
  | cons s w ih => exact ih.comp (step_cotransverse_three s)

lemma evalWord_cotransverse_two (w : List (Step 2)) :
    Cotransverse (evalWord w) := by
  induction w with
  | nil =>
      intro A B hAB
      exact hAB
  | cons s w ih => exact ih.comp (step_cotransverse_two s)

lemma evalWord_cotransverse_four (w : List (Step 4)) :
    Cotransverse (evalWord w) := by
  induction w with
  | nil =>
      intro A B hAB
      exact hAB
  | cons s w ih => exact ih.comp (step_cotransverse_four s)

theorem generated_cotransverse_three {f : Cube 3 → Cube 3}
    (hf : Generated f) : Cotransverse f := by
  rcases hf with ⟨w, rfl⟩
  exact evalWord_cotransverse_three w

theorem generated_cotransverse_two {f : Cube 2 → Cube 2}
    (hf : Generated f) : Cotransverse f := by
  rcases hf with ⟨w, rfl⟩
  exact evalWord_cotransverse_two w

theorem generated_cotransverse_four {f : Cube 4 → Cube 4}
    (hf : Generated f) : Cotransverse f := by
  rcases hf with ⟨w, rfl⟩
  exact evalWord_cotransverse_four w

lemma evalWord_generated {n : Nat} (w : List (Step n)) :
    Generated (evalWord w) :=
  ⟨w, rfl⟩

/-! ## Dimensions zero, one, and two -/

abbrev RankOne2 := RankVertex 2 1

def swap2 : Equiv.Perm (Fin 2) := Equiv.swap 0 1

/-- The four possibilities for the map on the two rank-one vertices:
identity, transposition, and the two constant maps. -/
def representativeWord2 (ρ : Fin 4) : List (Step 2) :=
  if ρ = 0 then []
  else if ρ = 1 then [.perm swap2]
  else if ρ = 2 then [.fold 0 1 (by decide)]
  else [.fold 0 1 (by decide), .perm swap2]

def normalMap2 (ρ : Fin 4) : Cube 2 → Cube 2 :=
  evalWord (representativeWord2 ρ)

def Normalizes2 (a : RankOne2 → RankOne2) (ρ : Fin 4) : Prop :=
  ∀ A, (a A).1 = normalMap2 ρ A.1

instance instDecidableNormalizes2 (a : RankOne2 → RankOne2) (ρ : Fin 4) :
    Decidable (Normalizes2 a ρ) := by
  unfold Normalizes2
  exact @Fintype.decidableForallFintype _ _
    (fun A => inferInstance) inferInstance

def LowDimensionTwoCertificate : Prop :=
  ∀ a : RankOne2 → RankOne2, ∃ ρ : Fin 4, Normalizes2 a ρ

instance instDecidableLowDimensionTwoCertificate :
    Decidable LowDimensionTwoCertificate := by
  unfold LowDimensionTwoCertificate
  let byA : DecidablePred fun a : RankOne2 → RankOne2 =>
      ∃ ρ : Fin 4, Normalizes2 a ρ := fun a =>
    @Fintype.decidableExistsFintype _ _
      (fun ρ => instDecidableNormalizes2 a ρ) inferInstance
  exact @Fintype.decidableForallFintype _ _ byA inferInstance

theorem low_dimension_two_certificate :
    ∀ a : RankOne2 → RankOne2, ∃ ρ : Fin 4, Normalizes2 a ρ := by
  change LowDimensionTwoCertificate
  decide

theorem cotransverse_normal_form_two (f : Cube 2 → Cube 2)
    (hf : Cotransverse f) : ∃ ρ : Fin 4, f = normalMap2 ρ := by
  let a : RankOne2 → RankOne2 := fun A =>
    ⟨f A.1, by simpa [A.2] using rank_preservation f hf A.1⟩
  rcases low_dimension_two_certificate a with ⟨ρ, hone⟩
  refine ⟨ρ, ?_⟩
  let g := normalMap2 ρ
  have hggenerated : Generated g := evalWord_generated (representativeWord2 ρ)
  have hg : Cotransverse g := generated_cotransverse_two hggenerated
  funext A
  have hle : A.card ≤ 2 := by
    simpa using Finset.card_le_univ A
  have hcases : A.card = 0 ∨ A.card = 1 ∨ A.card = 2 := by omega
  rcases hcases with hzero | honecard | htwo
  · have hA : A = ∅ := Finset.card_eq_zero.mp hzero
    rw [hA]
    change f ∅ = g ∅
    exact (fixes_bottom f hf).trans (fixes_bottom g hg).symm
  · simpa [a, g] using hone (⟨A, honecard⟩ : RankOne2)
  · have hA : A = (Finset.univ : Cube 2) := by
      apply (Finset.card_eq_iff_eq_univ A).mp
      simpa using htwo
    rw [hA]
    change f Finset.univ = g Finset.univ
    exact (fixes_top f hf).trans (fixes_top g hg).symm

theorem cotransverse_generated_two (f : Cube 2 → Cube 2)
    (hf : Cotransverse f) : Generated f := by
  rcases cotransverse_normal_form_two f hf with ⟨ρ, rfl⟩
  exact evalWord_generated (representativeWord2 ρ)

theorem dimension_two (f : Cube 2 → Cube 2) :
    Cotransverse f ↔ Generated f :=
  ⟨cotransverse_generated_two f, generated_cotransverse_two⟩

lemma step_cotransverse_zero (s : Step 0) : Cotransverse s.eval := by
  cases s with
  | perm σ => exact permMap_cotransverse σ
  | fold p q hpq => exact (hpq (Subsingleton.elim p q)).elim

lemma step_cotransverse_one (s : Step 1) : Cotransverse s.eval := by
  cases s with
  | perm σ => exact permMap_cotransverse σ
  | fold p q hpq => exact (hpq (Subsingleton.elim p q)).elim

lemma evalWord_cotransverse_zero (w : List (Step 0)) :
    Cotransverse (evalWord w) := by
  induction w with
  | nil =>
      intro A B hAB
      exact hAB
  | cons s w ih => exact ih.comp (step_cotransverse_zero s)

lemma evalWord_cotransverse_one (w : List (Step 1)) :
    Cotransverse (evalWord w) := by
  induction w with
  | nil =>
      intro A B hAB
      exact hAB
  | cons s w ih => exact ih.comp (step_cotransverse_one s)

theorem generated_cotransverse_zero {f : Cube 0 → Cube 0}
    (hf : Generated f) : Cotransverse f := by
  rcases hf with ⟨w, rfl⟩
  exact evalWord_cotransverse_zero w

theorem generated_cotransverse_one {f : Cube 1 → Cube 1}
    (hf : Generated f) : Cotransverse f := by
  rcases hf with ⟨w, rfl⟩
  exact evalWord_cotransverse_one w

theorem cotransverse_eq_id_zero (f : Cube 0 → Cube 0)
    (hf : Cotransverse f) : f = id := by
  funext A
  have hA : A = ∅ := by
    apply Finset.card_eq_zero.mp
    have hle : A.card ≤ 0 := by
      simpa using Finset.card_le_univ A
    omega
  simpa [hA] using fixes_bottom f hf

theorem cotransverse_eq_id_one (f : Cube 1 → Cube 1)
    (hf : Cotransverse f) : f = id := by
  funext A
  have hle : A.card ≤ 1 := by
    simpa using Finset.card_le_univ A
  have hcases : A.card = 0 ∨ A.card = 1 := by omega
  rcases hcases with hzero | hone
  · have hA : A = ∅ := Finset.card_eq_zero.mp hzero
    simpa [hA] using fixes_bottom f hf
  · have hA : A = (Finset.univ : Cube 1) := by
      apply (Finset.card_eq_iff_eq_univ A).mp
      simpa using hone
    simpa [hA] using fixes_top f hf

theorem dimension_zero (f : Cube 0 → Cube 0) :
    Cotransverse f ↔ Generated f := by
  constructor
  · intro hf
    rw [cotransverse_eq_id_zero f hf]
    exact generated_id
  · exact generated_cotransverse_zero

theorem dimension_one (f : Cube 1 → Cube 1) :
    Cotransverse f ↔ Generated f := by
  constructor
  · intro hf
    rw [cotransverse_eq_id_one f hf]
    exact generated_id
  · exact generated_cotransverse_one

/-! ## The proposed three-dimensional counterexample -/

/-- The table of the map proposed in the proof of Theorem 3.1.16 of the
2010 paper. Coordinates here are numbered `0,1,2`. -/
def oldMap (A : Cube 3) : Cube 3 :=
  if A.card = 0 then ∅
  else if A.card = 1 then {(2 : Fin 3)}
  else if A = {(0 : Fin 3), (2 : Fin 3)} then {(0 : Fin 3), (2 : Fin 3)}
  else if A.card = 2 then {(1 : Fin 3), (2 : Fin 3)}
  else Finset.univ

/-- The alleged counterexample is the composite of the comparators on
coordinates `(0,2)` and `(1,2)`, both oriented towards coordinate `2`. -/
theorem oldMap_factorization :
    oldMap = comparator (2 : Fin 3) 1 ∘ comparator (2 : Fin 3) 0 := by
  decide

theorem oldMap_generated : Generated oldMap := by
  rw [oldMap_factorization]
  exact (generated_comparator 2 1 (by decide)).comp
    (generated_comparator 2 0 (by decide))

theorem oldMap_cotransverse : Cotransverse oldMap :=
  generated_cotransverse_three oldMap_generated

/-! ## The six-cycle in dimension three -/

abbrev RankOne3 := RankVertex 3 1
abbrev RankTwo3 := RankVertex 3 2

/-- A cyclic permutation of the three coordinates. Its orientation is
irrelevant; both orientations induce the even rotations of the incidence
cycle. -/
def cycle3 : Equiv.Perm (Fin 3) :=
  (Equiv.swap (0 : Fin 3) 1).trans (Equiv.swap (1 : Fin 3) 2)

def cycle3Squared : Equiv.Perm (Fin 3) := cycle3.trans cycle3

/-- One fold, corresponding up to conjugacy to the map `a` in the paper. -/
def wordA3 : List (Step 3) :=
  [.fold 0 1 (by decide)]

/-- The map `b = a r a`. -/
def wordB3 : List (Step 3) :=
  wordA3 ++ [.perm cycle3] ++ wordA3

/-- The map `d = a r² a`. -/
def wordD3 : List (Step 3) :=
  wordA3 ++ [.perm cycle3Squared] ++ wordA3

/-- The map `c = (a r²)b`. Recall that the head of a word is applied
first. -/
def wordC3 : List (Step 3) :=
  wordB3 ++ [.perm cycle3Squared] ++ wordA3

/-- The five representatives: the automorphism case and the four balanced
sign-word orbits `a,b,d,c` from the proof. -/
def representativeWord3 (ρ : Fin 5) : List (Step 3) :=
  if ρ = 0 then []
  else if ρ = 1 then wordA3
  else if ρ = 2 then wordB3
  else if ρ = 3 then wordD3
  else wordC3

/-- A three-dimensional normal form: an automorphism on either side of one
of the five orbit representatives. -/
def normalMap3 (σ : Equiv.Perm (Fin 3)) (ρ : Fin 5)
    (τ : Equiv.Perm (Fin 3)) : Cube 3 → Cube 3 :=
  permMap σ ∘ evalWord (representativeWord3 ρ) ∘ permMap τ

lemma normalMap3_generated (σ : Equiv.Perm (Fin 3)) (ρ : Fin 5)
    (τ : Equiv.Perm (Fin 3)) : Generated (normalMap3 σ ρ τ) := by
  exact (generated_perm σ).comp
    ((evalWord_generated (representativeWord3 ρ)).comp (generated_perm τ))

def IncidencePreserving3 (a : RankOne3 → RankOne3)
    (b : RankTwo3 → RankTwo3) : Prop :=
  ∀ A B, DirectedEdge A.1 B.1 → DirectedEdge (a A).1 (b B).1

instance instDecidableIncidencePreserving3
    (a : RankOne3 → RankOne3) (b : RankTwo3 → RankTwo3) :
    Decidable (IncidencePreserving3 a b) := by
  unfold IncidencePreserving3
  let rows : DecidablePred fun A : RankOne3 =>
      ∀ B : RankTwo3,
        DirectedEdge A.1 B.1 → DirectedEdge (a A).1 (b B).1 :=
    fun A => @Fintype.decidableForallFintype _ _
      (fun B => inferInstance) inferInstance
  exact @Fintype.decidableForallFintype _ _ rows inferInstance

def Normalizes3 (a : RankOne3 → RankOne3) (b : RankTwo3 → RankTwo3)
    (σ : Equiv.Perm (Fin 3)) (ρ : Fin 5) (τ : Equiv.Perm (Fin 3)) : Prop :=
  (∀ A, (a A).1 = normalMap3 σ ρ τ A.1) ∧
  (∀ B, (b B).1 = normalMap3 σ ρ τ B.1)

instance instDecidableNormalizes3 (a : RankOne3 → RankOne3)
    (b : RankTwo3 → RankTwo3) (σ : Equiv.Perm (Fin 3)) (ρ : Fin 5)
    (τ : Equiv.Perm (Fin 3)) : Decidable (Normalizes3 a b σ ρ τ) := by
  unfold Normalizes3
  let oneDecidable : Decidable
      (∀ A, (a A).1 = normalMap3 σ ρ τ A.1) :=
    @Fintype.decidableForallFintype _ _ (fun A => inferInstance) inferInstance
  let twoDecidable : Decidable
      (∀ B, (b B).1 = normalMap3 σ ρ τ B.1) :=
    @Fintype.decidableForallFintype _ _ (fun B => inferInstance) inferInstance
  letI := oneDecidable
  letI := twoDecidable
  infer_instance

def HasNormalForm3 (a : RankOne3 → RankOne3)
    (b : RankTwo3 → RankTwo3) : Prop :=
  ∃ (σ τ : Equiv.Perm (Fin 3)) (ρ : Fin 5), Normalizes3 a b σ ρ τ

instance instDecidableHasNormalForm3 (a : RankOne3 → RankOne3)
    (b : RankTwo3 → RankTwo3) : Decidable (HasNormalForm3 a b) := by
  unfold HasNormalForm3
  let byRho (σ τ : Equiv.Perm (Fin 3)) :
      DecidablePred fun ρ : Fin 5 => Normalizes3 a b σ ρ τ :=
    fun ρ => instDecidableNormalizes3 a b σ ρ τ
  let byTau (σ : Equiv.Perm (Fin 3)) : DecidablePred fun τ =>
      ∃ ρ : Fin 5, Normalizes3 a b σ ρ τ := fun τ =>
    @Fintype.decidableExistsFintype _ _ (byRho σ τ) inferInstance
  let bySigma : DecidablePred fun σ : Equiv.Perm (Fin 3) =>
      ∃ τ, ∃ ρ : Fin 5, Normalizes3 a b σ ρ τ := fun σ =>
    @Fintype.decidableExistsFintype _ _ (byTau σ) inferInstance
  exact @Fintype.decidableExistsFintype _ _ bySigma inferInstance

def IncidenceNormalFormCertificate3 : Prop :=
  ∀ (a : RankOne3 → RankOne3) (b : RankTwo3 → RankTwo3),
    IncidencePreserving3 a b → HasNormalForm3 a b

instance instDecidableIncidenceNormalFormCertificate3 :
    Decidable IncidenceNormalFormCertificate3 := by
  unfold IncidenceNormalFormCertificate3
  let byB (a : RankOne3 → RankOne3) : DecidablePred fun b =>
      IncidencePreserving3 a b → HasNormalForm3 a b :=
    fun b => inferInstance
  let byA : DecidablePred fun a : RankOne3 → RankOne3 =>
      ∀ b : RankTwo3 → RankTwo3,
        IncidencePreserving3 a b → HasNormalForm3 a b := fun a =>
    @Fintype.decidableForallFintype _ _ (byB a) inferInstance
  exact @Fintype.decidableForallFintype _ _ byA inferInstance

/-- Finite certificate for the `C₆` generation lemma. It ranges only over
the two maps on the three vertices in each part of the bipartition
(`3^3 · 3^3 = 729` assignments). The five normal forms are exactly the
four balanced sign-word orbits and the constant-sign (automorphism) case
listed in the manuscript. -/
theorem incidence_normal_form_three :
    ∀ (a : RankOne3 → RankOne3) (b : RankTwo3 → RankTwo3),
      (∀ A B, DirectedEdge A.1 B.1 → DirectedEdge (a A).1 (b B).1) →
      ∃ (σ τ : Equiv.Perm (Fin 3)) (ρ : Fin 5),
        (∀ A, (a A).1 = normalMap3 σ ρ τ A.1) ∧
        (∀ B, (b B).1 = normalMap3 σ ρ τ B.1) := by
  change IncidenceNormalFormCertificate3
  set_option maxRecDepth 100000 in
    decide

/-- Every cotransverse endomorphism of the three-cube has one of the normal
forms obtained from the four `C₆` fold orbits. -/
theorem cotransverse_normal_form_three (f : Cube 3 → Cube 3)
    (hf : Cotransverse f) :
    ∃ (σ τ : Equiv.Perm (Fin 3)) (ρ : Fin 5), f = normalMap3 σ ρ τ := by
  let a : RankOne3 → RankOne3 := fun A =>
    ⟨f A.1, by simpa [A.2] using rank_preservation f hf A.1⟩
  let b : RankTwo3 → RankTwo3 := fun B =>
    ⟨f B.1, by simpa [B.2] using rank_preservation f hf B.1⟩
  have hab : ∀ A B, DirectedEdge A.1 B.1 →
      DirectedEdge (a A).1 (b B).1 := by
    intro A B hAB
    exact hf hAB
  rcases incidence_normal_form_three a b hab with
    ⟨σ, τ, ρ, hone, htwo⟩
  refine ⟨σ, τ, ρ, ?_⟩
  let g := normalMap3 σ ρ τ
  have hggenerated : Generated g := normalMap3_generated σ ρ τ
  have hg : Cotransverse g := generated_cotransverse_three hggenerated
  funext A
  have hle : A.card ≤ 3 := by
    simpa using Finset.card_le_univ A
  have hcases : A.card = 0 ∨ A.card = 1 ∨ A.card = 2 ∨ A.card = 3 := by
    omega
  rcases hcases with hzero | honecard | htwocard | hthree
  · have hA : A = ∅ := Finset.card_eq_zero.mp hzero
    rw [hA]
    change f ∅ = g ∅
    exact (fixes_bottom f hf).trans (fixes_bottom g hg).symm
  · simpa [a, g] using hone (⟨A, honecard⟩ : RankOne3)
  · simpa [b, g] using htwo (⟨A, htwocard⟩ : RankTwo3)
  · have hA : A = (Finset.univ : Cube 3) := by
      apply (Finset.card_eq_iff_eq_univ A).mp
      simpa using hthree
    rw [hA]
    change f Finset.univ = g Finset.univ
    exact (fixes_top f hf).trans (fixes_top g hg).symm

theorem cotransverse_generated_three (f : Cube 3 → Cube 3)
    (hf : Cotransverse f) : Generated f := by
  rcases cotransverse_normal_form_three f hf with ⟨σ, τ, ρ, rfl⟩
  exact normalMap3_generated σ ρ τ

/-- There is no counterexample in dimension three. -/
theorem dimension_three (f : Cube 3 → Cube 3) :
    Cotransverse f ↔ Generated f :=
  ⟨cotransverse_generated_three f, generated_cotransverse_three⟩

/-- The bipartition-preserving endomorphisms of the middle-rank incidence
cycle. -/
def incidenceEndomorphisms3 :
    Finset ((RankOne3 → RankOne3) × (RankTwo3 → RankTwo3)) :=
  Finset.univ.filter fun h => IncidencePreserving3 h.1 h.2

/-- The `C₆` count `3(2 + choose 6 3) = 66`, checked on the equivalent
pair of three-point incidence maps. -/
theorem incidenceEndomorphisms3_card : incidenceEndomorphisms3.card = 66 := by
  decide

abbrev NormalParameter3 :=
  Equiv.Perm (Fin 3) × Fin 5 × Equiv.Perm (Fin 3)

def normalMaps3 : Finset (Cube 3 → Cube 3) :=
  Finset.univ.image fun p : NormalParameter3 => normalMap3 p.1 p.2.1 p.2.2

theorem normalMaps3_card : normalMaps3.card = 66 := by
  set_option maxRecDepth 100000 in
    decide

def cotransverseMaps3 : Finset (Cube 3 → Cube 3) :=
  Finset.univ.filter Cotransverse

theorem normalMaps3_eq_cotransverseMaps3 :
    normalMaps3 = cotransverseMaps3 := by
  ext f
  simp only [normalMaps3, cotransverseMaps3, Finset.mem_image,
    Finset.mem_filter, Finset.mem_univ, true_and]
  constructor
  · rintro ⟨p, rfl⟩
    exact generated_cotransverse_three
      (normalMap3_generated p.1 p.2.1 p.2.2)
  · intro hf
    rcases cotransverse_normal_form_three f hf with ⟨σ, τ, ρ, h⟩
    exact ⟨(σ, ρ, τ), h.symm⟩

/-- There are exactly 66 cotransverse endomorphisms of the three-cube. -/
theorem cotransverseMaps3_card : cotransverseMaps3.card = 66 := by
  rw [← normalMaps3_eq_cotransverseMaps3]
  exact normalMaps3_card

/-! ## The cited coface-factorization corollary -/

/-- A heterodimensional map is generated, relative to a predicate selecting
the coface composites, when it is a generated level map followed by such a
coface composite. -/
def GeneratedHom {m n : Nat} (CofaceComposite : (Cube m → Cube n) → Prop)
    (u : Cube m → Cube n) : Prop :=
  ∃ (v : Cube m → Cube m) (δ : Cube m → Cube n),
    Generated v ∧ CofaceComposite δ ∧ u = δ ∘ v

/-- Formal deduction used in the source-at-most-three corollary. The first
hypothesis is the existence part of the cited unique coface factorization;
uniqueness is not needed here. -/
theorem hom_equality_of_coface_factorization {m n : Nat}
    (CofaceComposite : (Cube m → Cube n) → Prop)
    (hcoface : ∀ δ, CofaceComposite δ → Cotransverse δ)
    (hfactor : ∀ u, Cotransverse u →
      ∃ (v : Cube m → Cube m) (δ : Cube m → Cube n),
        Cotransverse v ∧ CofaceComposite δ ∧ u = δ ∘ v)
    (hlevel : ∀ v : Cube m → Cube m, Cotransverse v ↔ Generated v)
    (u : Cube m → Cube n) :
    Cotransverse u ↔ GeneratedHom CofaceComposite u := by
  constructor
  · intro hu
    rcases hfactor u hu with ⟨v, δ, hv, hδ, huv⟩
    exact ⟨v, δ, (hlevel v).mp hv, hδ, huv⟩
  · rintro ⟨v, δ, hv, hδ, rfl⟩
    exact (hcoface δ hδ).comp ((hlevel v).mpr hv)

theorem source_zero_of_coface_factorization {n : Nat}
    (CofaceComposite : (Cube 0 → Cube n) → Prop)
    (hcoface : ∀ δ, CofaceComposite δ → Cotransverse δ)
    (hfactor : ∀ u, Cotransverse u →
      ∃ (v : Cube 0 → Cube 0) (δ : Cube 0 → Cube n),
        Cotransverse v ∧ CofaceComposite δ ∧ u = δ ∘ v)
    (u : Cube 0 → Cube n) :
    Cotransverse u ↔ GeneratedHom CofaceComposite u :=
  hom_equality_of_coface_factorization CofaceComposite hcoface hfactor
    dimension_zero u

theorem source_one_of_coface_factorization {n : Nat}
    (CofaceComposite : (Cube 1 → Cube n) → Prop)
    (hcoface : ∀ δ, CofaceComposite δ → Cotransverse δ)
    (hfactor : ∀ u, Cotransverse u →
      ∃ (v : Cube 1 → Cube 1) (δ : Cube 1 → Cube n),
        Cotransverse v ∧ CofaceComposite δ ∧ u = δ ∘ v)
    (u : Cube 1 → Cube n) :
    Cotransverse u ↔ GeneratedHom CofaceComposite u :=
  hom_equality_of_coface_factorization CofaceComposite hcoface hfactor
    dimension_one u

theorem source_two_of_coface_factorization {n : Nat}
    (CofaceComposite : (Cube 2 → Cube n) → Prop)
    (hcoface : ∀ δ, CofaceComposite δ → Cotransverse δ)
    (hfactor : ∀ u, Cotransverse u →
      ∃ (v : Cube 2 → Cube 2) (δ : Cube 2 → Cube n),
        Cotransverse v ∧ CofaceComposite δ ∧ u = δ ∘ v)
    (u : Cube 2 → Cube n) :
    Cotransverse u ↔ GeneratedHom CofaceComposite u :=
  hom_equality_of_coface_factorization CofaceComposite hcoface hfactor
    dimension_two u

theorem source_three_of_coface_factorization {n : Nat}
    (CofaceComposite : (Cube 3 → Cube n) → Prop)
    (hcoface : ∀ δ, CofaceComposite δ → Cotransverse δ)
    (hfactor : ∀ u, Cotransverse u →
      ∃ (v : Cube 3 → Cube 3) (δ : Cube 3 → Cube n),
        Cotransverse v ∧ CofaceComposite δ ∧ u = δ ∘ v)
    (u : Cube 3 → Cube n) :
    Cotransverse u ↔ GeneratedHom CofaceComposite u :=
  hom_equality_of_coface_factorization CofaceComposite hcoface hfactor
    dimension_three u

/-! ## The path-graph witness in dimension four -/

/-- The edge set of the path graph `0—1—2—3`, represented by two-element
subsets of its vertex set. -/
def PathEdge4 (A : Cube 4) : Prop :=
  A = {(0 : Fin 4), (1 : Fin 4)} ∨
  A = {(1 : Fin 4), (2 : Fin 4)} ∨
  A = {(2 : Fin 4), (3 : Fin 4)}

instance instDecidablePathEdge4 (A : Cube 4) : Decidable (PathEdge4 A) := by
  unfold PathEdge4
  infer_instance

def PathAdjacent4 (p q : Fin 4) : Prop := PathEdge4 {p, q}

instance instDecidablePathAdjacent4 (p q : Fin 4) :
    Decidable (PathAdjacent4 p q) := by
  unfold PathAdjacent4
  infer_instance

/-- The map `F` of the manuscript. -/
def F (A : Cube 4) : Cube 4 :=
  if A.card = 0 then ∅
  else if A.card = 1 then {(0 : Fin 4)}
  else if A.card = 2 then
    if PathEdge4 A then {(0 : Fin 4), (1 : Fin 4)}
    else {(0 : Fin 4), (2 : Fin 4)}
  else if A.card = 3 then {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)}
  else Finset.univ

private lemma edge_empty_singleton_four :
    DirectedEdge (∅ : Cube 4) {(0 : Fin 4)} := by
  decide

private lemma edge_singleton_path_four :
    DirectedEdge ({(0 : Fin 4)} : Cube 4) {0, 1} := by
  decide

private lemma edge_singleton_nonpath_four :
    DirectedEdge ({(0 : Fin 4)} : Cube 4) {0, 2} := by
  decide

private lemma edge_path_triple_four :
    DirectedEdge ({(0 : Fin 4), (1 : Fin 4)} : Cube 4) {0, 1, 2} := by
  decide

private lemma edge_nonpath_triple_four :
    DirectedEdge ({(0 : Fin 4), (2 : Fin 4)} : Cube 4) {0, 1, 2} := by
  decide

private lemma edge_triple_top_four :
    DirectedEdge ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Cube 4)
      Finset.univ := by
  decide

/-- `F` takes every directed edge to a directed edge. The proof follows the
five inclusions displayed after formula (5.2) in the manuscript. -/
theorem F_cotransverse : Cotransverse F := by
  intro A B hAB
  have hcard : B.card = A.card + 1 := DirectedEdge.card_eq hAB
  have hB_le : B.card ≤ 4 := by
    simpa using Finset.card_le_univ B
  have hA_le : A.card ≤ 3 := by omega
  have hcases : A.card = 0 ∨ A.card = 1 ∨ A.card = 2 ∨ A.card = 3 := by
    omega
  rcases hcases with hzero | hone | htwo | hthree
  · have hB : B.card = 1 := by omega
    simpa [F, hzero, hB] using edge_empty_singleton_four
  · have hB : B.card = 2 := by omega
    by_cases hp : PathEdge4 B
    · simpa [F, hone, hB, hp] using edge_singleton_path_four
    · simpa [F, hone, hB, hp] using edge_singleton_nonpath_four
  · have hB : B.card = 3 := by omega
    by_cases hp : PathEdge4 A
    · simpa [F, htwo, hB, hp] using edge_path_triple_four
    · simpa [F, htwo, hB, hp] using edge_nonpath_triple_four
  · have hB : B.card = 4 := by omega
    simpa [F, hthree, hB] using edge_triple_top_four

/-- A graph has no twins when every two distinct vertices have different
open neighborhoods. This is the explicit no-twins statement for `P₄`. -/
def Path4NoTwins : Prop :=
  ∀ p q : Fin 4, p ≠ q →
    ∃ k : Fin 4, k ≠ p ∧ k ≠ q ∧
      ((PathAdjacent4 p k ∧ ¬PathAdjacent4 q k) ∨
       (¬PathAdjacent4 p k ∧ PathAdjacent4 q k))

instance instDecidablePath4NoTwins : Decidable Path4NoTwins := by
  unfold Path4NoTwins
  let byQ (p : Fin 4) : DecidablePred fun q : Fin 4 => p ≠ q →
      ∃ k : Fin 4, k ≠ p ∧ k ≠ q ∧
        ((PathAdjacent4 p k ∧ ¬PathAdjacent4 q k) ∨
         (¬PathAdjacent4 p k ∧ PathAdjacent4 q k)) := fun q => by
    let existsDecidable : Decidable
        (∃ k : Fin 4, k ≠ p ∧ k ≠ q ∧
          ((PathAdjacent4 p k ∧ ¬PathAdjacent4 q k) ∨
           (¬PathAdjacent4 p k ∧ PathAdjacent4 q k))) :=
      @Fintype.decidableExistsFintype _ _
        (fun k => inferInstance) inferInstance
    letI := existsDecidable
    infer_instance
  let byP : DecidablePred fun p : Fin 4 =>
      ∀ q : Fin 4, p ≠ q →
        ∃ k : Fin 4, k ≠ p ∧ k ≠ q ∧
          ((PathAdjacent4 p k ∧ ¬PathAdjacent4 q k) ∨
           (¬PathAdjacent4 p k ∧ PathAdjacent4 q k)) := fun p =>
    @Fintype.decidableForallFintype _ _ (byQ p) inferInstance
  exact @Fintype.decidableForallFintype _ _ byP inferInstance

theorem path4_no_twins : Path4NoTwins := by
  decide

lemma F_on_pair {p k : Fin 4} (hpk : p ≠ k) :
    F {p, k} = if PathAdjacent4 p k then {0, 1} else {0, 2} := by
  simp [F, PathAdjacent4, Finset.card_pair hpk]

/-- `F` globally folds no pair. This is the graph-theoretic heart of the
dimension-four example. -/
theorem F_no_global_fold (p q : Fin 4) (hpq : p ≠ q) :
    ¬GloballyFolds F p q := by
  intro hfold
  rcases path4_no_twins p q hpq with
    ⟨k, hkp, hkq, hdistinguishes⟩
  have hpnot : p ∉ ({k} : Cube 4) := by simpa [ne_comm] using hkp
  have hqnot : q ∉ ({k} : Cube 4) := by simpa [ne_comm] using hkq
  have heq := hfold ({k} : Cube 4) hpnot hqnot
  have hpk : p ≠ k := hkp.symm
  have hqk : q ≠ k := hkq.symm
  rcases hdistinguishes with ⟨hpathp, hnpathq⟩ | ⟨hnpathp, hpathq⟩
  · rw [F_on_pair hpk, F_on_pair hqk, if_pos hpathp, if_neg hnpathq] at heq
    exact (by decide : ({(0 : Fin 4), (1 : Fin 4)} : Cube 4) ≠ {0, 2}) heq
  · rw [F_on_pair hpk, F_on_pair hqk, if_neg hnpathp, if_pos hpathq] at heq
    exact (by decide : ({(0 : Fin 4), (2 : Fin 4)} : Cube 4) ≠ {0, 1}) heq

theorem F_not_injective : ¬Injective F := by
  intro hinjective
  have heq : F ({(0 : Fin 4)} : Cube 4) = F {1} := by
    decide
  have := hinjective heq
  exact (by decide : ({(0 : Fin 4)} : Cube 4) ≠ {1}) this

/-- The explicit four-dimensional map is not a word in permutations and
folds. -/
theorem F_not_generated : ¬Generated F := by
  intro hgenerated
  rcases first_fold_obstruction hgenerated F_not_injective with
    ⟨p, q, hpq, hfold⟩
  exact F_no_global_fold p q hpq hfold

/-- Strict inclusion at level four. -/
theorem strict_in_dimension_four :
    ∃ f : Cube 4 → Cube 4, Cotransverse f ∧ ¬Generated f :=
  ⟨F, F_cotransverse, F_not_generated⟩

end CotransverseDimensionFour
